# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk14

# используем режим обычного пользователя для сборки проекта.
sudo: false
install: true
script:
  - mvn install
services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE auto_crash;" -U postgres

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почтуyouremail@smtp.ru если сборка упала
notifications:
  email:
    recipients:
      - zubov.vp@yandex.ru
    on_success: never # default: change
    on_failure: always # defa,ult: always

  env:
    global:
      - CODECOV_TOKEN="ec576115-84b5-4c5c-bf84-f107a3212638"